export const epg = [
  {
    id: "6f3caa7f-5b11-4edb-998e-80d4baa03373",
    description:
      "Bounty hunter Boba Fett & mercenary Fennec Shand navigate the underworld when they return to Tatooine to claim Jabba the Hutt's old turf.",
    title: "The Book of Boba Fett",
    isYesterday: true,
    since: "2022-10-17T23:50:00",
    till: "2022-10-18T00:55:00",
    channelUuid: "16fdfefe-e466-4090-bc1a-57c43937f826",
    image:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg",
    country: "Ghana",
    Year: "2021–",
    Rated: "TV-14",
    Released: "29 Dec 2021",
    Runtime: "N/A",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "N/A",
    Writer: "Jon Favreau",
    Actors: "Temuera Morrison, Ming-Na Wen, Matt Berry",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "20,147",
    imdbID: "tt13668894",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.0/10" }],
    rating: 3,
  },
  {
    id: "f8fa7e21-6a8a-4ccc-8859-6f61a31f2f55",
    description:
      "The series will follow Carrie, Miranda and Charlotte as they navigate the journey from the complicated reality of life and friendship in their 30s to the even more complicated reality of life and friendship in their 50s.",
    title: "And Just Like That...",
    since: "2022-10-18T00:55:00",
    till: "2022-10-18T02:35:00",
    channelUuid: "16fdfefe-e466-4090-bc1a-57c43937f826",
    image:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/1CqkiWeuwlaMswG02q3mBmraiDM.jpg",
    country: "Mozambique",
    Year: "2021–",
    Rated: "TV-MA",
    Released: "09 Dec 2021",
    Runtime: "N/A",
    Genre: "Comedy, Drama, Romance",
    Director: "N/A",
    Writer: "Michael Patrick King, Darren Star",
    Actors: "Sarah Jessica Parker, Cynthia Nixon, Kristin Davis",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Metascore: "N/A",
    imdbRating: "5.4",
    imdbVotes: "18,366",
    imdbID: "tt13819960",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
    Ratings: [{ Source: "Internet Movie Database", Value: "5.4/10" }],
    rating: 1,
  }];